# Generated by Django 5.1 on 2024-10-04 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HousingPictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(upload_to='housing_pictures/')),
                ('picture_type', models.CharField(choices=[('building', '物件写真'), ('floor', '間取り図')], default='building', max_length=10)),
                ('order', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'housing_pictures',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Housings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('zip_code', models.CharField(max_length=7, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('distance', models.CharField(max_length=30, null=True)),
                ('floor', models.CharField(max_length=10, null=True)),
                ('house_kind', models.CharField(max_length=20, null=True)),
                ('construction', models.IntegerField(null=True)),
                ('floor_number', models.IntegerField(null=True)),
                ('building_picture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='building_pictures', to='house.housingpictures')),
                ('floor_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='floor_plans', to='house.housingpictures')),
            ],
            options={
                'db_table': 'housing',
            },
        ),
        migrations.AddField(
            model_name='housingpictures',
            name='housing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='house.housings'),
        ),
    ]
